name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  labels:  # id of input
    description: 'comma separated labels'
    required: false
outputs:
  status: # output will be available to future steps
    description: 'status of whether we took action'
runs:
  using: 'node16'
  main: 'dist/index.js'
