name: 'charles-actions-pr-toolkit-label-on-files'
description: 'Label PR on files changed'
inputs:
  labels:
    description: 'comma separated labels'
    required: false
  files_modified:
    description: 'only labels if at least one file for this glob was modified'
    required: false
  files_deleted:
    description: 'only labels if at least one file for this glob was deleted'
    required: false
outputs:
  status: # output will be available to future steps
    description: 'status of whether we took action'
runs:
  using: 'node16'
  main: 'dist/index.js'
